# Use with: docker-compose -f docker-compose.yaml -f docker-compose.java.yaml up
services:
  loan:
    # Disable Python loan service
    profiles:
      - disabled

  loan-java:
    build:
      context: ./loan-java
      dockerfile: Dockerfile
    container_name: loan
    hostname: loan
    image: martian-bank-loan-java
    restart: always
    environment:
      DB_URL: mongodb://root:example@mongo:27017
      SERVICE_PROTOCOL: http
    networks:
      - bankapp-network
